name: StickerBridge
options:
  deploymentTarget:
    iOS: '15.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    PRODUCT_BUNDLE_IDENTIFIER: com.iwanehu.stickerbridge
    TARGETED_DEVICE_FAMILY: '1,2'
targets:
  StickerBridge:
    type: application
    platform: iOS
    sources:
      - path: StickerBridge
        excludes: [Resources]
      - path: StickerBridge/Resources/web
        type: folder
        buildPhase: resources
      - path: StickerBridge/Resources/detect-favorites.js
        buildPhase: resources
    info:
      path: StickerBridge/Info.plist
      properties:
        CFBundleDisplayName: Sticker Bridge
        LSApplicationQueriesSchemes: [whatsapp]
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
